version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: evgenyklyukin/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/backend_media
  
  frontend:
    image: evgenyklyukin/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    image: evgenyklyukin/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media