version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/backend_media/
  
  frontend:
    build: ./frontend/
    env_file: .env
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/
  
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles/
      - media:/media/