volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: evgenyklyukin/kittygram_backend
    container_name: kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media/
    depends_on:
      - db
  frontend:
    image: evgenyklyukin/kittygram_frontend
    container_name: kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  
  gateway:
    image: evgenyklyukin/kittygram_gateway
    container_name: kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
      - frontend
